// tools/e2e-tests/apps/typescript/imports/ui/Hello.tsx
import { useState } from 'react';

export const Hello = () => {
  const [counter, setCounter] = useState(0);

  const increment = () => {
    setCounter(counter + 1);
  };

  return (
    <div>
      <button onClick={increment}>Click Me</button>
      <p>You've pressed the button {counter} times.</p>
    </div>
  );
};

// tools/static-assets/skel-angular/imports/ui/hello.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-hello',
  standalone: true,
  template: `
    <div>
      <button (click)="increment()">Click Me</button>
      <p>You've pressed the button {{ counter }} times.</p>
    </div>
  `
})
export class HelloComponent {
  counter = 0;

  increment() {
    this.counter += 1;
  }
}
