// tools/static-assets/skel-tailwind/imports/ui/Hello.jsx
import React, { useState } from 'react';

export const Hello = () => {
  const [counter, setCounter] = useState(0);

  const increment = () => {
    setCounter(counter + 1);
  };

  return (
    <div className="mt-4">
      <button
        onClick={increment}
        className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
      >
        Click Me
      </button>
      <p>You've pressed the button <b>{counter}</b> times.</p>
    </div>
  );
};

// tools/static-assets/skel-vue/imports/ui/Hello.vue
<script setup>
import { ref } from 'vue'

const count = ref(0)

function increment() {
  count.value++
}
</script>

<template>
  <button @click="increment" class="bg-green-700 hover:bg-green-900 text-white py-2 px-4 rounded">Click Me</button>
  <p>
    You've pressed the button <strong>{{ count }}</strong> times.
  </p>
</template>
