// tools/e2e-tests/apps/solid/imports/ui/Hello.jsx
import { createSignal } from "solid-js";

export const Hello = () => {
  const [counter, setCounter] = createSignal(0);

  const increment = () => {
    setCounter(counter() + 1);
  };

  return (
    <div>
      <button onClick={increment}>Click Me</button>
      <p>You've pressed the button {counter()} times.</p>
    </div>
  );
}

// tools/static-assets/skel-typescript/imports/ui/Hello.tsx
import React, { useState } from 'react';

export const Hello = () => {
  const [counter, setCounter] = useState(0);

  const increment = () => {
    setCounter(counter + 1);
  };

  return (
    <div>
      <button onClick={increment}>Click Me</button>
      <p>You've pressed the button {counter} times.</p>
    </div>
  );
};
