// tools/e2e-tests/apps/vue/imports/ui/components/Info.vue
<script setup>
import { subscribe, autorun } from 'vue-meteor-tracker'
import { LinksCollection } from '/imports/api/links'

subscribe('links')
const links = autorun(() => LinksCollection.find({}).fetch()).result
</script>

<template>
  <h2 class="text-xl my-6 font-semibold">Learn Meteor!</h2>
  <ul class="list-disc underline">
    <li v-for="link of links" :key="link._id" class="hover:text-green-700">
      <a :href="link.url" target="_blank">{{ link.title }}</a>
    </li>
  </ul>
</template>

// tools/static-assets/skel-tailwind/imports/ui/Info.jsx
import React from 'react';
import { useTracker } from 'meteor/react-meteor-data';
import { LinksCollection } from '../api/links';

export const Info = () => {
  const links = useTracker(() => {
    return LinksCollection.find().fetch();
  });

  return (
    <div className="mt-4">
      <h2 className="font-bold">Learn Meteor!</h2>
      <ul className="list-disc ml-5">{links.map(
        link => <li key={link._id}>
          <a className="underline" href={link.url} target="_blank">{link.title}</a>
        </li>
      )}</ul>
    </div>
  );
};
