// tools/static-assets/skel-solid/imports/ui/Info.jsx
import { LinksCollection } from "../api/links";
import { createSignal, For } from "solid-js";
import { Tracker } from "meteor/tracker";

export const Info = () => {
  const [links, setLinks] = createSignal([]);

  Tracker.autorun(() => {
    setLinks(LinksCollection.find().fetch());
  });

  return (
    <div>
      <h2>Learn Meteor!</h2>
      <ul>
        <For each={links()}>{
          (link) =>
            <li>
              <a href={link.url} target="_blank">{link.title}</a>
            </li>
        }</For>
      </ul>
    </div>
  )

}

// tools/static-assets/skel-react/imports/ui/Info.jsx
import React from 'react';
import { useTracker } from 'meteor/react-meteor-data';
import { LinksCollection } from '../api/links';

export const Info = () => {
  const links = useTracker(() => {
    return LinksCollection.find().fetch();
  });

  return (
    <div>
      <h2>Learn Meteor!</h2>
      <ul>{links.map(
        link => <li key={link._id}>
          <a href={link.url} target="_blank">{link.title}</a>
        </li>
      )}</ul>
    </div>
  );

}
